# Generated by Django 4.2.6 on 2024-05-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OLXAuthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=50)),
                ('refresh_token', models.CharField(max_length=50)),
                ('access_token_expired_time', models.DateTimeField()),
                ('refresh_token_expired_time', models.DateTimeField()),
                ('olx_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
