# Generated by Django 4.2.6 on 2026-01-05 21:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tyreadderapp', '0079_pair_is_otomoto_pair_advert_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtoMotoAdvertData',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='otomoto_data', serialize=False, to='tyreadderapp.product')),
                ('otomoto_advert_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('otomoto_advert_status', models.CharField(blank=True, null=True)),
                ('is_autorefresh', models.BooleanField(default=False)),
                ('is_exported_to_olx', models.BooleanField(default=False)),
                ('ad_views_total', models.PositiveIntegerField(default=0)),
                ('ad_visits_total', models.PositiveIntegerField(default=0)),
                ('phone_views_total', models.PositiveIntegerField(default=0)),
                ('phone_calls_total', models.PositiveIntegerField(default=0)),
                ('messages_total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OtomotoAuthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default='', max_length=255)),
                ('refresh_token', models.CharField(default='', max_length=255)),
                ('access_token_expired_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PairOtoMotoAdvertData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('otomoto_advert_id', models.BigIntegerField(blank=True, null=True)),
                ('pair', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otomoto_advert', to='tyreadderapp.pair')),
            ],
        ),
    ]
