# Generated by Django 4.2.6 on 2026-01-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairotomotoadvertdata',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pairotomotoadvertdata',
            name='otomoto_advert_status',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pairotomotoadvertdata',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
