# Generated by Django 4.2.6 on 2026-01-16 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomoto', '0002_pairotomotoadvertdata_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otomotoauthdata',
            name='access_token_expired_time',
        ),
        migrations.AddField(
            model_name='otomotoauthdata',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 16, 30, 30, 965727, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otomotoauthdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
