# Generated by Django 4.2.6 on 2026-01-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomoto', '0003_remove_otomotoauthdata_access_token_expired_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otomotoauthdata',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
