# Generated by Django 4.2.6 on 2026-02-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomoto', '0004_otomotoauthdata_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otomotoauthdata',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otomotoauthdata',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
