# Generated by Django 4.2.6 on 2026-03-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomoto', '0005_alter_otomotoauthdata_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairotomotoadvertdata',
            name='is_autorefresh',
            field=models.BooleanField(default=False),
        ),
    ]
