# Generated by Django 4.2.6 on 2026-03-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomoto', '0006_pairotomotoadvertdata_is_autorefresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairotomotoadvertdata',
            name='ad_views_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairotomotoadvertdata',
            name='ad_visits_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairotomotoadvertdata',
            name='messages_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairotomotoadvertdata',
            name='phone_calls_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairotomotoadvertdata',
            name='phone_views_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
