# Generated by Django 4.2.6 on 2026-03-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomoto', '0007_pairotomotoadvertdata_ad_views_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otomotoadvertdata',
            name='last_synced_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pairotomotoadvertdata',
            name='last_synced_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
