# Generated by Django 4.2.6 on 2026-03-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otomoto', '0008_otomotoadvertdata_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otomotoadvertdata',
            name='otomoto_advert_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pairotomotoadvertdata',
            name='otomoto_advert_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
