# Generated by Django 4.2.6 on 2024-06-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_status_order_shipping_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='payout_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
