# Generated by Django 4.2.6 on 2025-01-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderpayment_payout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
