# Generated by Django 4.2.6 on 2025-01-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ext_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
