# Generated by Django 4.2.6 on 2025-04-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_company_address_order_company_apartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pal_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='position',
        ),
        migrations.AddField(
            model_name='order',
            name='pallet_type_error',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
