# Generated by Django 4.2.6 on 2025-09-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_courier_remove_order_pal_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='company_address',
            new_name='company_building',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='company_delivery',
            new_name='delivery_building',
        ),
    ]
