# Generated by Django 4.2.6 on 2025-10-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
