# Generated by Django 4.2.6 on 2025-10-24 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0056_alter_warehouse_location_alter_warehouse_name'),
        ('orders', '0014_order_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='tyreadderapp.product'),
        ),
    ]
