# Generated by Django 4.2.6 on 2025-11-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
