# Generated by Django 4.2.6 on 2024-06-11 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='shipping_amount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tax_fee',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart'),
        ),
    ]
