# Generated by Django 4.2.6 on 2024-11-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_order_status_remove_cart_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
