# Generated by Django 4.2.6 on 2024-12-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
