# Generated by Django 4.2.6 on 2024-12-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='city',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='email',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='full_name',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
