# Generated by Django 4.2.6 on 2025-01-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cart_city_alter_cart_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
