# Generated by Django 4.2.6 on 2025-01-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cart_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='self_pickup',
            field=models.BooleanField(default=True),
        ),
    ]
