# Generated by Django 4.2.6 on 2025-01-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_cart_self_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='self_pickup',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
