# Generated by Django 4.2.6 on 2025-03-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_cart_company_apartment_cart_company_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='city',
            new_name='company_address',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='regon',
        ),
        migrations.AddField(
            model_name='cart',
            name='company_delivery',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='first_name',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='last_name',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='nip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
