# Generated by Django 4.2.6 on 2025-09-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_cart_unique_user_cart_cart_unique_session_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='company_address',
            new_name='company_building',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='company_delivery',
            new_name='delivery_building',
        ),
    ]
