# Generated by Django 4.2.6 on 2025-10-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_rename_company_address_cart_company_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tyres_and_transport_gross_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
