# Generated by Django 4.2.6 on 2025-10-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_cart_delivery_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
