# Generated by Django 4.2.6 on 2025-10-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_cart_delivery_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_tyres_net_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
