# Generated by Django 5.1.3 on 2025-11-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_cart_total_tyres_net_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_gross_transportation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
