# Generated by Django 5.1.3 on 2025-11-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_cart_final_gross_transportation_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='company_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
