# Generated by Django 5.1.3 on 2025-11-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_alter_cart_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
