# Generated by Django 4.2.6 on 2025-11-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_alter_cart_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tyres_gross_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
