"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

from dotenv import load_dotenv

load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_9)c!0+3=f+)5zhiwdh)###l5$4gebypxikx60glc19mw+g%7u"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # os.environ.get("DEBUG")== 'TRUE'

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
    "164.92.130.1",
    "www.tirgumpanel.pl",
    "tirgumpanel.pl",
    "shop.tirgum.pl",
    ".tirgum.pl",  # wildcard subdomains
    
    # ".ngrok-free.app",   # allow ALL ngrok subdomains
    # ".ngrok.io",  
]


# 'http://localhost:3000/',
# 'http://127.0.0.1:8000/'

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 18,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication'
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "COERCE_DECIMAL_TO_STRING": False,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Tirgum API',
    'DESCRIPTION': 'Tires',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    'rest_framework.authtoken',
    "corsheaders",
    "drf_spectacular",

    # external
    "tyreadderapp",
    "otomoto.apps.OtomotoConfig",
    "users",
    "import_export",
    "django_filters",
    "django_tables2",
    "olx",
    "cart",
    'orders',
    'libs',
    'allegro',
    # 'otomoto',
    'wishlist',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # "users.middleware.UserApprovalMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DB_HOST = os.environ.get("POSTGRES_HOST")
DB_PORT = os.environ.get("POSTGRES_PORT")
DB_NAME = os.environ.get("POSTGRES_DB")
DB_USER = os.environ.get("POSTGRES_USER")
DB_PASSWORD = os.environ.get("POSTGRES_PASSWORD")

# Make sure that we use postgres if all the env variables are set on prod, else use sqlite on local machines
if DB_HOST and DB_PORT and DB_NAME and DB_USER and DB_PASSWORD:
    print("-----=====>>>",DB_HOST,DB_PORT )
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": DB_NAME,
            "USER": DB_USER,
            "PASSWORD": DB_PASSWORD,
            "HOST": DB_HOST,
            "PORT": DB_PORT,
            "ATOMIC_REQUESTS": True,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    # {
    #     "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    # },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

CORS_ALLOWED_ORIGINS = ["https://www.tirgumpanel.pl", "https://tirgumpanel.pl", "http://localhost:3000",
                        "http://127.0.0.1:8000", "http://0.0.0.0",
                        "http://localhost", "http://164.92.130.1", "https://shop.tirgum.pl", "https://*.tirgum.pl"]

CSRF_TRUSTED_ORIGINS = ["https://www.tirgumpanel.pl", "https://tirgumpanel.pl", "http://localhost:8000",
                        "http://127.0.0.1:8000"]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  

STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

#STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
AUTH_USER_MODEL = 'users.User'
LOGIN_REDIRECT_URL = 'shop'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = "login"

CORS_ORIGIN_ALLOW_ALL = True

# Mail Gun Settings
# settings.py
MAILGUN_API_KEY = "b9c8a8cd8ea444e1ee5105b89bb63a7d-8a084751-3cf66560"
MAILGUN_DOMAIN = "mail.tirgumpanel.pl"
MAILGUN_FROM_EMAIL = "brad@mail.tirgumpanel.pl"
# MAILGUN_API_KEY = os.environ.get("MAILGUN_API_KEY")
# MAILGUN_DOMAIN = os.environ.get("MAILGUN_DOMAIN")
# MAILGUN_FROM_EMAIL = os.environ.get("MAILGUN_FROM_EMAIL")

CORS_ORIGIN_ALLOW_ALL = True

FAKTUROWNIA_URL = os.environ.get("FAKTUROWNIA_URL", "https://biuro2281.fakturownia.pl")
FAKTUROWNIA_TOKEN = os.environ.get("FAKTUROWNIA_TOKEN", "OvFKEAHY-WiihaaCLZvX")


DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'logfile.log',
        },
    },
    'root': {
        'handlers': ['file'],
        'level': 'DEBUG',  # Adjust the logging level as needed
        },
}

MODEL_PATH = os.path.join(BASE_DIR, 'tyreadderapp', 'ml', 'price_predictor.pkl')
ENCODERS_PATH = os.path.join(BASE_DIR, 'tyreadderapp', 'ml', 'encoders.pkl')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'biuro2.tirgum@gmail.com'
EMAIL_HOST_PASSWORD = 'cdrr clko ehnq yzlr'

DEFAULT_FROM_EMAIL = 'ravichovatiya121@gmail.com'
CLIENT_NOTIFICATION_EMAIL = ' biuro2.tirgum@gmail.com '


OTOMOTO = {
    "CLIENT_ID": "1434",
    "CLIENT_SECRET": "a2d0cc4f28df802ec62e0012bde78ba6",
    "REDIRECT_URI": "http://www.tirgumpanel.pl/otomoto/callback",
    "TOKEN_URL": "https://www.otomoto.pl/api/open/oauth/token",
    "API_BASE_URL": "https://www.otomoto.pl/api/open/api/v1",
    "AUTHORIZE_URL": "https://www.otomoto.pl/open/oauth/authorize",
}