# Generated by Django 4.2.6 on 2024-12-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allegroauthdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=10000, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=10000, null=True)),
                ('access_token_expired_time', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expired_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
