# Generated by Django 4.2.6 on 2024-12-27 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allegro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allegroauthdata',
        ),
    ]
