# Generated by Django 4.2.6 on 2026-03-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allegro', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allegroauthdata',
        ),
    ]
