# Generated by Django 4.2.6 on 2026-03-13 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0091_image_allegro_expires_at_image_allegro_image_url'),
        ('allegro', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllegroAdvertData',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='allegro_single_advert_data', serialize=False, to='tyreadderapp.product')),
                ('allegro_advert_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
