# Generated by Django 4.2.6 on 2024-05-06 09:29

from django.db import migrations, models
import django.db.models.deletion
import tyreadderapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Marka')),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=30, unique=True)),
                ('width', models.PositiveSmallIntegerField()),
                ('profile', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('OFD', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('FW', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tread_to_x_winner', models.CharField(blank=True, choices=[('half', 'Half'), ('euro', 'Euro'), ('industrial_m', 'Industrial M'), ('industrial_d', 'Industrial D'), ('odbiór_osobisty', 'Odbiór Osobisty')], max_length=30, null=True)),
                ('tread_to_y_winner', models.CharField(blank=True, choices=[('half', 'Half'), ('euro', 'Euro'), ('industrial_m', 'Industrial M'), ('industrial_d', 'Industrial D'), ('odbiór_osobisty', 'Odbiór Osobisty')], max_length=30, null=True)),
                ('stack_winner', models.CharField(blank=True, choices=[('half', 'Half'), ('euro', 'Euro'), ('industrial_m', 'Industrial M'), ('industrial_d', 'Industrial D'), ('odbiór_osobisty', 'Odbiór Osobisty')], max_length=30, null=True)),
                ('tread_to_x_quantity', models.PositiveSmallIntegerField(default=0)),
                ('tread_to_y_quantity', models.PositiveSmallIntegerField(default=0)),
                ('stack_quantity', models.PositiveSmallIntegerField(default=0)),
                ('stack_rem_space_height', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('is_steer', models.BooleanField(default=False)),
                ('is_drive', models.BooleanField(default=False)),
                ('is_trailer', models.BooleanField(default=False)),
                ('is_m_s', models.BooleanField(default=False)),
                ('is_3pmsf', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyreadderapp.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Tread_Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.CharField(choices=[('Sterująca', 'Sterująca'), ('Napęd', 'Napęd'), ('Naczepa', 'Naczepa'), ('Wszystkie', 'Wszystkie')], default='4', max_length=50)),
                ('direction', models.CharField(choices=[('Symetryczna', 'Symetryczna'), ('Kierunkowa', 'Kierunkowa')], default='Kierunkowa', max_length=50)),
                ('sips_quantity', models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='4', max_length=50)),
                ('new_tire_price', models.FloatField(blank=True, null=True)),
                ('new_tire_tread_depth', models.FloatField(blank=True, null=True)),
                ('recommended_pressure', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyreadderapp.brand')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tyreadderapp.size')),
                ('tread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyreadderapp.tread')),
            ],
        ),
        migrations.CreateModel(
            name='Tread_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('tread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyreadderapp.tread_character')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('status', models.CharField(choices=[('Do dodania', 'To Add'), ('W sprzedaży', 'On Sale'), ('Sprzedane', 'Sold')], default='Do dodania', max_length=20)),
                ('is_tire_bead_damaged', models.BooleanField(default=False, verbose_name='Uszkodzona stopka')),
                ('is_incised', models.BooleanField(default=False, verbose_name='Nacinana')),
                ('front_repairs', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0, verbose_name='Naprawy gwoździowe')),
                ('is_side_repair', models.BooleanField(default=False, verbose_name='Naprawy boczne')),
                ('is_visible_cracks', models.BooleanField(default=False, verbose_name='Widoczne pęknięcia')),
                ('is_braked', models.BooleanField(default=False, verbose_name='Hamulec')),
                ('is_braked_repair', models.BooleanField(default=False, verbose_name='Nap. po hamulcu')),
                ('is_shoulder_repair', models.BooleanField(default=False, verbose_name='Naprawa barku')),
                ('is_cosmetology', models.BooleanField(default=False, verbose_name='Kosmetyka')),
                ('is_toothed_out', models.BooleanField(default=False, verbose_name='Wyząbkowana')),
                ('is_retreaded', models.BooleanField(default=False, verbose_name='Bieżnikowana')),
                ('is_ruts', models.BooleanField(default=False, verbose_name='Koleiny')),
                ('is_circumventional_cut', models.BooleanField(default=False, verbose_name='Wycięty rowek')),
                ('tread_depth_min', models.IntegerField(verbose_name='Bieżnik MIN')),
                ('tread_depth_max', models.IntegerField(verbose_name='Bieżnik MAX')),
                ('dot', models.IntegerField(blank=True, null=True)),
                ('net_price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cena netto')),
                ('supplier_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('warehouse', models.PositiveSmallIntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')], default=0)),
                ('is_label_printed', models.BooleanField(default=False)),
                ('set_number', models.IntegerField(blank=True, null=True)),
                ('is_allegro', models.BooleanField(default=False, verbose_name='Allegro')),
                ('is_otomoto', models.BooleanField(default=False, verbose_name='Otomoto')),
                ('is_merchant_center', models.BooleanField(default=False, verbose_name='Google Merchant')),
                ('is_olx', models.BooleanField(default=False, verbose_name='Olx')),
                ('is_olx_active', models.BooleanField(default=False, verbose_name='Olx_Advert_Active')),
                ('olx_advert_id', models.PositiveIntegerField(blank=True, null=True)),
                ('olx_response', models.TextField(blank=True, null=True)),
                ('olx_active_advert_response', models.TextField(blank=True, null=True)),
                ('advert_title', models.CharField(max_length=200)),
                ('advert_description', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyreadderapp.brand')),
                ('pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tyreadderapp.pair')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tyreadderapp.size')),
                ('tread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyreadderapp.tread')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=tyreadderapp.models.get_image_name)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyreadderapp.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='tyreadderap_name_4c5bb0_idx'),
        ),
    ]
