# Generated by Django 4.2.6 on 2024-05-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tread_character',
            name='axis',
        ),
        migrations.RemoveField(
            model_name='tread_character',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='tread_character',
            name='recommended_pressure',
        ),
    ]
