# Generated by Django 4.2.6 on 2024-05-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0002_remove_tread_character_axis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mht', models.PositiveIntegerField()),
                ('X', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pallete',
                'verbose_name_plural': 'Palletes',
            },
        ),
    ]