# Generated by Django 4.2.6 on 2024-06-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0003_pallete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pallete',
            name='gross_price',
        ),
    ]
