# Generated by Django 4.2.6 on 2024-07-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0004_remove_pallete_gross_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_text',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
