# Generated by Django 4.2.6 on 2024-07-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0005_product_additional_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='net_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cena netto'),
        ),
    ]
