# Generated by Django 4.2.6 on 2024-07-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0006_alter_product_net_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='blocked_pair',
            field=models.BooleanField(default=False),
        ),
    ]
