# Generated by Django 4.2.6 on 2024-08-09 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0007_pair_blocked_pair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tread_character',
            name='sips_quantity',
        ),
    ]
