# Generated by Django 4.2.6 on 2024-08-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0008_remove_tread_character_sips_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tread_character',
            name='new_tire_tread_depth',
        ),
    ]
