# Generated by Django 4.2.6 on 2024-08-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0009_remove_tread_character_new_tire_tread_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tread_character',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tread_character',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tread_character',
            name='tread',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
