# Generated by Django 4.2.6 on 2024-08-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0010_alter_tread_character_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Tread_Depth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('tread', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('new_tire_tread_depth', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
