# Generated by Django 4.2.6 on 2024-08-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0011_new_tread_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='net_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cena netto'),
        ),
    ]
