# Generated by Django 4.2.6 on 2024-09-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0014_product_is_front_heat_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
