# Generated by Django 4.2.6 on 2024-09-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0015_size_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='pair_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pair',
            name='pair_is_olx',
            field=models.BooleanField(default=False, verbose_name='Olx'),
        ),
        migrations.AddField(
            model_name='pair',
            name='pair_is_olx_active',
            field=models.BooleanField(default=False, verbose_name='Olx_Advert_Active'),
        ),
        migrations.AddField(
            model_name='pair',
            name='pair_olx_active_advert_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pair',
            name='pair_olx_advert_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pair',
            name='pair_olx_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pair',
            name='pair_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pair',
            name='pair_title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
