# Generated by Django 4.2.6 on 2024-09-25 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0016_pair_pair_description_pair_pair_is_olx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pair_images/')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairimages', to='tyreadderapp.pair')),
            ],
        ),
    ]
