# Generated by Django 4.2.6 on 2024-10-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0017_pairimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='olx_advert_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
