# Generated by Django 4.2.6 on 2024-10-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0010_alter_tread_character_brand_and_more'),
        ('tyreadderapp', '0018_product_olx_advert_status'),
    ]

    operations = [
    ]
