# Generated by Django 4.2.6 on 2024-12-13 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0020_company_pallete_pallet_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallete',
            name='pallet_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pallete',
            name='transportation_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='size',
            name='pallete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pallete_size', to='tyreadderapp.pallete'),
        ),
    ]
