# Generated by Django 4.2.6 on 2024-12-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0021_pallete_pallet_cost_pallete_transportation_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_update_status',
            field=models.BooleanField(default=False),
        ),
    ]
