# Generated by Django 4.2.6 on 2025-01-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0022_product_image_update_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allegro_advert_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='allegro_api_respose',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='allegro_status',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Allegro response'),
        ),
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, null=True,max_length=255, verbose_name='ean_number'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_allegro_active',
            field=models.BooleanField(default=False, verbose_name='Allegro_Advert_Active'),
        ),
    ]
