# Generated by Django 4.2.6 on 2025-01-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0023_product_allegro_advert_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre_Ean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean_brand', models.CharField(max_length=255)),
                ('ean_tread', models.CharField(max_length=255)),
                ('ean_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ean_profile', models.CharField(blank=True, max_length=20, null=True)),
                ('ean_diameter', models.CharField(max_length=20)),
                ('ean_size', models.CharField(max_length=50)),
                ('ean_li', models.CharField(max_length=20)),
                ('ean_si', models.CharField(max_length=20)),
                ('ean', models.BigIntegerField(unique=True)),
            ],
        ),
    ]
