# Generated by Django 4.2.6 on 2025-02-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0024_tyre_ean'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallete',
            name='empty_pal_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
