# Generated by Django 4.2.6 on 2025-02-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0025_pallete_empty_pal_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationcost',
            name='pal_discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pallete',
            name='empty_pal_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
