# Generated by Django 4.2.6 on 2025-02-28 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0026_transportationcost_pal_discounted_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['size']},
        ),
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tyreadderapp.product'),
        ),
    ]
