# Generated by Django 4.2.6 on 2025-02-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0027_alter_brand_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='image',
            name='position',
        ),
    ]
