# Generated by Django 4.2.6 on 2025-03-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0028_alter_image_options_remove_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='product_listing_status',
            field=models.CharField(choices=[('new', 'New'), ('listed', 'Listed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product_listing_status',
            field=models.CharField(choices=[('new', 'New'), ('listed', 'Listed')], default='new', max_length=20),
        ),
    ]
