# Generated by Django 4.2.6 on 2025-03-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0029_pair_product_listing_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pair',
            old_name='product_listing_status',
            new_name='pair_listing_status',
        ),
    ]
