# Generated by Django 4.2.6 on 2025-03-27 11:35

from django.db import migrations, models
import tyreadderapp.generate_filename
import tyreadderapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0030_rename_product_listing_status_pair_pair_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=tyreadderapp.generate_filename.OverwriteStorage(), upload_to=tyreadderapp.models.get_image_name),
        ),
    ]
