# Generated by Django 4.2.6 on 2025-03-28 06:15

from django.db import migrations, models
import tyreadderapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0031_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tyreadderapp.models.get_image_name),
        ),
    ]
