# Generated by Django 4.2.6 on 2025-03-28 06:16

from django.db import migrations, models
import tyreadderapp.generate_filename
import tyreadderapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0032_image_updated_at_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=tyreadderapp.generate_filename.OverwriteStorage(), upload_to=tyreadderapp.models.get_image_name),
        ),
    ]
