# Generated by Django 4.2.6 on 2025-03-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0033_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='force_update',
            field=models.BooleanField(default=False),
        ),
    ]
