# Generated by Django 4.2.6 on 2025-07-02 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0034_image_force_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
