# Generated by Django 4.2.6 on 2025-08-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0035_pair_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
