# Generated by Django 4.2.6 on 2025-08-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0036_size_description_size_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
