# Generated by Django 4.2.6 on 2025-08-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0037_product_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarTread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyreadderapp.brand')),
                ('similar_tread_combinations', models.ManyToManyField(blank=True, to='tyreadderapp.similartread')),
                ('tread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyreadderapp.tread')),
            ],
        ),
    ]
