# Generated by Django 4.2.6 on 2025-08-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0038_similartread'),
    ]

    operations = [
        migrations.AddField(
            model_name='tread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tread_images/'),
        ),
    ]
