# Generated by Django 5.1.3 on 2025-08-19 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0039_tread_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedProductFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mój filtr', max_length=100)),
                ('only_on_sale', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tyreadderapp.brand')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tyreadderapp.size')),
                ('tread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tyreadderapp.tread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_product_filter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
