# Generated by Django 4.2.6 on 2025-08-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0041_selectedproductfilter_is_front_heat_repair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
