# Generated by Django 4.2.6 on 2025-08-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0042_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tread',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
