# Generated by Django 4.2.6 on 2025-08-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0043_tread_has_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedproductfilter',
            name='is_braked',
            field=models.BooleanField(default=False, verbose_name='Hamulec'),
        ),
        migrations.AddField(
            model_name='selectedproductfilter',
            name='is_braked_repair',
            field=models.BooleanField(default=False, verbose_name='Nap. po hamulcu'),
        ),
        migrations.AddField(
            model_name='selectedproductfilter',
            name='is_circumventional_cut',
            field=models.BooleanField(default=False, verbose_name='Wycięty rowek'),
        ),
        migrations.AddField(
            model_name='selectedproductfilter',
            name='is_cosmetology',
            field=models.BooleanField(default=False, verbose_name='Kosmetyka'),
        ),
        migrations.AddField(
            model_name='selectedproductfilter',
            name='is_retreaded',
            field=models.BooleanField(default=False, verbose_name='Bieżnikowana'),
        ),
        migrations.AddField(
            model_name='selectedproductfilter',
            name='is_ruts',
            field=models.BooleanField(default=False, verbose_name='Koleiny'),
        ),
        migrations.AddField(
            model_name='selectedproductfilter',
            name='is_shoulder_repair',
            field=models.BooleanField(default=False, verbose_name='Naprawa barku'),
        ),
        migrations.AddField(
            model_name='selectedproductfilter',
            name='is_side_repair',
            field=models.BooleanField(default=False, verbose_name='Naprawy boczne'),
        ),
        migrations.AddField(
            model_name='selectedproductfilter',
            name='is_toothed_out',
            field=models.BooleanField(default=False, verbose_name='Wyząbkowana'),
        ),
        migrations.AddField(
            model_name='selectedproductfilter',
            name='is_visible_cracks',
            field=models.BooleanField(default=False, verbose_name='Widoczne pęknięcia'),
        ),
    ]
