# Generated by Django 4.2.6 on 2025-09-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0044_selectedproductfilter_is_braked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedproductfilter',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='selectedproductfilter',
            name='only_on_sale',
        ),
        migrations.RemoveField(
            model_name='selectedproductfilter',
            name='updated_at',
        ),
    ]
