# Generated by Django 4.2.6 on 2025-09-15 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0045_remove_selectedproductfilter_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedproductfilter',
            name='isdrive',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Oś napędowa'),
        ),
        migrations.AddField(
            model_name='selectedproductfilter',
            name='issteer',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Oś sterująca'),
        ),
        migrations.AddField(
            model_name='selectedproductfilter',
            name='istrailer',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Oś naczepowa'),
        ),
        migrations.AddField(
            model_name='selectedproductfilter',
            name='oldest_dot',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Najstarszy dot'),
        ),
        migrations.AddField(
            model_name='selectedproductfilter',
            name='tread_depth_min',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(4)], verbose_name='Minimalny bieżnik'),
        ),
    ]
