# Generated by Django 4.2.6 on 2025-09-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0046_selectedproductfilter_isdrive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedproductfilter',
            name='is_braked',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Hamulec'),
        ),
        migrations.AlterField(
            model_name='selectedproductfilter',
            name='is_braked_repair',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Nap. po hamulcu'),
        ),
        migrations.AlterField(
            model_name='selectedproductfilter',
            name='is_circumventional_cut',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Wycięty rowek'),
        ),
        migrations.AlterField(
            model_name='selectedproductfilter',
            name='is_cosmetology',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Kosmetyka'),
        ),
        migrations.AlterField(
            model_name='selectedproductfilter',
            name='is_front_heat_repair',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Naprawa czoła na gorąco'),
        ),
        migrations.AlterField(
            model_name='selectedproductfilter',
            name='is_retreaded',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Bieżnikowana'),
        ),
        migrations.AlterField(
            model_name='selectedproductfilter',
            name='is_ruts',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Koleiny'),
        ),
        migrations.AlterField(
            model_name='selectedproductfilter',
            name='is_shoulder_repair',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Naprawa barku'),
        ),
        migrations.AlterField(
            model_name='selectedproductfilter',
            name='is_side_repair',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Naprawy boczne'),
        ),
        migrations.AlterField(
            model_name='selectedproductfilter',
            name='is_tire_bead_damaged',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Uszkodzona stopka'),
        ),
        migrations.AlterField(
            model_name='selectedproductfilter',
            name='is_toothed_out',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Wyząbkowana'),
        ),
        migrations.AlterField(
            model_name='selectedproductfilter',
            name='is_visible_cracks',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Widoczne pęknięcia'),
        ),
    ]
