# Generated by Django 4.2.6 on 2025-10-01 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0047_alter_selectedproductfilter_is_braked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tread',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='tread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tyreadderapp.tread'),
        ),
    ]
