# Generated by Django 4.2.6 on 2025-10-15 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0050_remove_product_warehouse_row_stockitem_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tyreadderapp.rack'),
        ),
        migrations.AddField(
            model_name='product',
            name='row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tyreadderapp.row'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tyreadderapp.warehouse'),
        ),
    ]
