# Generated by Django 4.2.6 on 2025-10-15 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0052_staple_product_staple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tyreadderapp.rack'),
        ),
        migrations.AlterField(
            model_name='product',
            name='row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tyreadderapp.row'),
        ),
        migrations.AlterField(
            model_name='product',
            name='staple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tyreadderapp.staple'),
        ),
    ]
