# Generated by Django 4.2.6 on 2025-10-15 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0053_alter_product_rack_alter_product_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='tyreadderapp.row'),
        ),
    ]
