# Generated by Django 4.2.6 on 2025-10-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0054_rack_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks', to='tyreadderapp.row'),
        ),
    ]
