# Generated by Django 4.2.6 on 2025-11-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0056_alter_warehouse_location_alter_warehouse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='otomoto_ad_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
