# Generated by Django 4.2.6 on 2025-11-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0057_product_otomoto_ad_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='otomoto_ad_id',
            new_name='otomoto_advert_id',
        ),
    ]
