# Generated by Django 4.2.6 on 2025-11-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0058_rename_otomoto_ad_id_product_otomoto_advert_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='otomoto_advert_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
