# Generated by Django 4.2.6 on 2025-11-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0059_product_otomoto_advert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='otomoto_advert_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
