# Generated by Django 4.2.6 on 2025-12-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0060_alter_product_otomoto_advert_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='otomoto_advert_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
