# Generated by Django 4.2.6 on 2025-12-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0061_product_otomoto_advert_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='otomoto_advert_status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
