# Generated by Django 4.2.6 on 2025-12-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0062_alter_product_otomoto_advert_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_otomoto',
            new_name='is_otomoto_advert_created',
        ),
    ]
