# Generated by Django 4.2.6 on 2025-12-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0063_rename_is_otomoto_product_is_otomoto_advert_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_otomoto_advert_created',
            field=models.BooleanField(default=False, verbose_name='Otomoto_advert_created'),
        ),
    ]
