# Generated by Django 4.2.6 on 2025-12-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0064_alter_product_is_otomoto_advert_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_otomoto_advert_activated',
            field=models.BooleanField(default=False, verbose_name='Otomoto_advert_activated'),
        ),
    ]
