# Generated by Django 4.2.6 on 2025-12-11 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0065_product_is_otomoto_advert_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtoMotoAdvertData',
            fields=[
                ('otomoto_advert_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tyreadderapp.product')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
