# Generated by Django 4.2.6 on 2025-12-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0066_otomotoadvertdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtoMotoAdvertData',
        ),
    ]
