# Generated by Django 4.2.6 on 2025-12-11 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0067_delete_otomotoadvertdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtoMotoAdvertData',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='otomoto_data', serialize=False, to='tyreadderapp.product')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
