# Generated by Django 4.2.6 on 2025-12-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0068_otomotoadvertdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='otomotoadvertdata',
            name='ad_views_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otomotoadvertdata',
            name='ad_visits_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otomotoadvertdata',
            name='messages_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otomotoadvertdata',
            name='phone_calls_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otomotoadvertdata',
            name='phone_views_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
