# Generated by Django 4.2.6 on 2025-12-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0069_otomotoadvertdata_ad_views_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='otomoto_advert_status',
        ),
        migrations.AddField(
            model_name='otomotoadvertdata',
            name='otomoto_advert_status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
