# Generated by Django 4.2.6 on 2025-12-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0070_remove_product_otomoto_advert_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='otomoto_advert_id',
        ),
    ]
