# Generated by Django 4.2.6 on 2025-12-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0071_remove_product_otomoto_advert_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='otomotoadvertdata',
            name='otomoto_advert_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
