# Generated by Django 4.2.6 on 2025-12-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0072_otomotoadvertdata_otomoto_advert_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtoMotoAdvertData',
        ),
    ]
