# Generated by Django 4.2.6 on 2025-12-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0073_delete_otomotoadvertdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='otomoto_advert_description',
        ),
    ]
