# Generated by Django 4.2.6 on 2025-12-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0074_remove_product_otomoto_advert_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_item_sold',
            field=models.BooleanField(default=False),
        ),
    ]
