# Generated by Django 4.2.6 on 2025-12-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0075_product_is_item_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_item_sold',
        ),
        migrations.AddField(
            model_name='product',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Sold'),
        ),
    ]
