# Generated by Django 4.2.6 on 2025-12-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0076_remove_product_is_item_sold_product_sold_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sold_date',
            new_name='sold_at',
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date On Sale'),
        ),
    ]
