# Generated by Django 4.2.6 on 2026-01-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0077_rename_sold_date_product_sold_at_product_on_sale_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='is_otomoto_pair_advert_created',
            field=models.BooleanField(default=False),
        ),
    ]
