# Generated by Django 4.2.6 on 2026-01-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0078_pair_is_otomoto_pair_advert_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='is_otomoto_pair_advert_activated',
            field=models.BooleanField(default=False),
        ),
    ]
