# Generated by Django 4.2.6 on 2026-01-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0079_pair_is_otomoto_pair_advert_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='on_sale_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold_at',
        ),
    ]
