# Generated by Django 4.2.6 on 2026-01-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0080_remove_product_on_sale_at_remove_product_sold_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_sale_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date On Sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Sold'),
        ),
    ]
