# Generated by Django 4.2.6 on 2026-02-03 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0081_product_on_sale_at_product_sold_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tyreadderapp.pair'),
        ),
    ]
