# Generated by Django 4.2.6 on 2026-02-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0082_alter_product_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_tire_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new_tire_tread_depth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
