# Generated by Django 4.2.6 on 2026-02-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0083_product_new_tire_price_product_new_tire_tread_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='tread_character',
            name='shop_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
