# Generated by Django 4.2.6 on 2026-02-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0084_tread_character_shop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tread_character',
            name='optimized_tyre_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
