# Generated by Django 4.2.6 on 2026-02-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0086_new_tread_depth_optimized_tyre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='optimized_tyre_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
