# Generated by Django 4.2.6 on 2026-02-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0087_product_optimized_tyre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_tire_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_tire_tread_depth',
        ),
    ]
