# Generated by Django 4.2.6 on 2026-02-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0088_remove_product_new_tire_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_tire_price',
            field=models.FloatField(blank=True, null=True, verbose_name='New Tire Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_tire_tread_depth',
            field=models.FloatField(blank=True, null=True, verbose_name='New Tire Tread Depth'),
        ),
    ]
