# Generated by Django 4.2.6 on 2026-03-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0089_product_new_tire_price_product_new_tire_tread_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='allegro_brand_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
