# Generated by Django 4.2.6 on 2026-03-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyreadderapp', '0090_brand_allegro_brand_id_brand_country_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='allegro_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='allegro_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
