# Generated by Django 4.2.6 on 2024-05-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payuauth',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payuauth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='payuauth',
            name='expires_in',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payuauth',
            name='grant_type',
            field=models.CharField(blank=True, default='client_credentials', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payuauth',
            name='token_type',
            field=models.CharField(blank=True, default='Bearer', max_length=255, null=True),
        ),
    ]
