# Generated by Django 4.2.6 on 2025-01-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0002_alter_payuauth_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payuauth',
            name='expires_in',
        ),
    ]
