# Generated by Django 4.2.6 on 2025-01-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0003_remove_payuauth_expires_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='payuauth',
            name='expires_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
