# Generated by Django 4.2.6 on 2025-03-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_company_apartment_user_company_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apartment_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registry_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='regon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street_number',
        ),
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_delivery',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
