# Generated by Django 4.2.6 on 2025-09-29 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company_address',
            new_name='company_building',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='company_delivery',
            new_name='delivery_building',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
